### ISSUE TITLE
Grid question

### ISSUE THREAD

**Issue by anna-pokhilenko** [anna-pokhilenko/web-design-2-independent-project#1]
@hellachella

Hi, it's me)
The issue is with my grid that I am trying to figure out. I am in doubt about how to use it properly to place the contact button (orange).

**Comment by hellachella** [comment]
Can you show me where you want it placed?

**Comment by anna-pokhilenko** [comment]
Sure, sorry!

<img width="1024" alt="Screen Shot 2020-11-25 at 8 56 31 AM" src="https://user-images.githubusercontent.com/55008926/100236809-26a64800-2efc-11eb-86a0-845bd10648dc.png">

**Comment by anna-pokhilenko** [comment]
Now I was worried about the contact button on the right.

And I also will have to place all these other orange circles on the left behind my text. What will be the best approach?

**Comment by hellachella** [comment]
I would try using grid-column and grid-row. The following tutorial will explain it better than I can in text. Follow this link and watch from right around the the 23 minute mark. 

https://www.youtube.com/watch?v=jV8B24rSN5o

**Comment by anna-pokhilenko** [comment]
videos like that are so helpful, thank you!

**Comment by anna-pokhilenko** [comment]
would you recommend a different way for the other highlight circles on the left side?

**Comment by hellachella** [comment]
They are decorative and not integral to the grid, I would position them using z-index and absolute positioning.

**Comment by hellachella** [comment]
Alternately, you could play around with SVG + live text. There is info about that in the SVG portion of the course.

**Comment by hellachella** [comment]
Be sure and include aria-labels if you do that. Have them read out the name of the link only and leave out info about the decorative circles. `<a href="#" aria-label="Paper Bag Annual Report"></a>`

**Comment by anna-pokhilenko** [comment]
@hellachella
@mackenzierose

Hello) 
I am working on the responsibility of my home page, and I spotted that some of the changes in my code won't be reflected in the browser. Even if I push my changes and close the tab and reload the page and so on...
Not sure what's going on.

**Comment by anna-pokhilenko** [comment]
oh, I guess it's working now!

**Comment by anna-pokhilenko** [comment]
@hellachella
@MacKenzieRose
@JessJodoin
@HannahDelaney

Hey-hey)
I am soo close to be done, but I have a couple of questions.

Q1: My navigation looks different on small screen sizes (320) even though the grid and everything is the same on all pages. I wonder why is it so?
Q2: My "Let's Talk!" paragraph doesn't align with other paragraphs on the About page. No idea why as well..
Q3: The biggest issue now is the overflow of my images on the small scree size on the Peachy Cider page. I was playing with overflow:hidden and I was resizing them in photosop with "Save for Web" but it didn't help much. I've attached the photo of how I was imagining the page would work out.

Thank you :)
<img width="90" alt="Screen Shot 2020-12-08 at 5 36 06 PM" src="https://user-images.githubusercontent.com/55008926/101549545-e1fac200-397b-11eb-9449-1ae6d81d8627.png">

**Comment by HannahDelaney** [comment]
Hey Anna! Cool site.

1. So for your nav, part of the issue is that while your grid areas are laid out the same, your pages all have different margins outside of the grid itself, and you've also used margins to centre your logo within it's own grid-area, which is a big part of why it looks a bit different on each page.

I would recommend adding a `body {margin: 0;}` to all of your pages, and then maybe a `padding: 1rem;` to your nav directly on each page. Then, rather than margins on the `.logo-small` class to align the logo, just add something like `text-align: center;` and then they will all have the same things added to them.

2. Your `.right-side-contact` class has `margin: .7em, 2.3em 4.5em 0;` on it right now, so it's lower that the other side by .7em. If you change that to 0 they will line up.

3. So you have a lot of huge width percentages on your images here, and they are all different. So even though you were adjusting to have a hidden overflow and so on, your text is not aligning to centre because there is a visible overflow for the images and they are all different sizes.

I would recommend you try adding a class like what we used to learn in the modulifier library, "img-flex". I use this for basically every image when I write websites. The class just needs to have `display: block` and `width: 100%` on it, and then be put on each image. It will help keeps things consistent. If you don't add this exact class at least make sure all the images have these elements (it's much more efficient to make this class and add it to each image than to apply those values to each different class you've made).

Then, you have some of the images not taking up the full width of all three grid-areas, so 100% will only fill 66% of the page (which is I'm assuming why you were making the max-width so big for some of them). Then you can play with paddings for the left and right sides, perhaps starting on individual images, to make them not be the full width of the page. You could also put padding on  a container class, so that everything has the same amount of white space on the sides. There are also just a few extra margins added to the sides of content here and there, and I think that may also be contributing to why your page looks inconsistent. Try removing those and using more .img-flex classes and paddings/margins on container elements, vs individual ones.

I hope that helps!

**Comment by anna-pokhilenko** [comment]
@hellachella
@MacKenzieRose
@JessJodoin
@HannahDelaney

Thank you, Hannah, that helped a lot!

I also ran into problems when my web won't respond to the grid I am creating in the media query. I am not sure why because the grid doesn't break (as it would do if the areas were not consistent). 
It just doesn't work and refers back to the other media queries. 

It happens at 60em Media Query on my Peachy Cider page.

I also struggle with how my navigation aligns on all the pages on the large screen sizes. It doesn't align properly even though I checked all the margins and paddings on the CSS files and was trying to adjust these but no luck for me...

**Comment by MacKenzieRose** [comment]
For your navigation, I'm assuming that the spacing between the elements is the concern, which changes between your Home and About pages. It looks like **your logo element only has a margin on the Home page**, but not on the About page, which is why there's inconsistent spacing.

I'm still trying to figure out what's happening with the last media query. Will comment again when I get it to work :)

**Comment by MacKenzieRose** [comment]
And we're back! Thank you to @HannahDelaney for figuring this one out ❤️ 

Around line 282, you've got a chunk of code that reads:
`"straight straight p2 p2"`
`"straight straight not not"`
` "straight purp oran blk"`

This kind of set up is making a non-rectangle shape for your "straight" section, so none of it is being applied. If you can change that last "straight" to just being an empty line, your media queries should start working.

As well, she recommends removing that extra margin on the `purple-circle` class so things line up nicely.

**Comment by anna-pokhilenko** [comment]
@MacKenzieRose and @HannahDelaney omg thank you soooooo much, you can't imagine how happy I am right now that you could help me figure out this grid thingy <3 
I could troubleshoot all other grids but that one drove me crazy haha

**Comment by anna-pokhilenko** [comment]
@hellachella
@MacKenzieRose
@JessJodoin
@HannahDelaney

hey)
I have a problem with SVGs
I have smushed them, but it annoys markbot and that's why I can't fix other issues...

The last image attached is how I see it by itself and not in HTML code.
<img width="508" alt="Screen Shot 2020-12-17 at 3 20 37 PM" src="https://user-images.githubusercontent.com/55008926/102539379-9c28b280-407b-11eb-98c3-42e0554e5350.png">
<img width="1063" alt="Screen Shot 2020-12-17 at 3 20 27 PM" src="https://user-images.githubusercontent.com/55008926/102539384-9df27600-407b-11eb-8000-48afc340ad23.png">
<img width="1088" alt="Screen Shot 2020-12-17 at 3 20 16 PM" src="https://user-images.githubusercontent.com/55008926/102539389-9fbc3980-407b-11eb-880a-4a50ac758fb4.png">

**Comment by anna-pokhilenko** [comment]
I've changed the svg code a bit but it still doesn't work, it's the code for the three dots navigation on all small screens

**Comment by anna-pokhilenko** [comment]
And right after I put aria-label on my SVG it disappears...

**Comment by JessJodoin** [comment]
Not sure if this will work but maybe try re-exporting them from illustrator as an svg, smush it again and add it to the index.html using the `<img>`. 

If you're wanting it to be like a hamburger nav, this is a great tutorial using checkboxes to make it work:

https://learn-the-web.algonquindesign.ca/topics/navigation/#toggle-navigation

(though, adding a hamburger nav will run you some accessibility issues from Markbot — it really hates them — so you'd have to remove the hamburger nav to hand it in and then re-add it so it's there when Chelle grades it)

**Comment by anna-pokhilenko** [comment]
@hellachella

**Request for grade**

This term we were focusing a lot on a grid structure, responsive design, and website performance. I was trying to keep all these aspects in mind when I coded the website and I used them a lot. 

My biggest focus was on grids and responsiveness of the website, so I spend most of my time figuring out the grid structure and the way my web will look on different screens. I feel like I could perform these tasks quite effectively but I still found that images interfere with the grid and create a bit of an overflow that I couldn't find a way to fix yet. On the other side, I feel like I implemented a good and consistent grid structure on all my pages. My weakest part was accessibility, I could have done better with this part of the web, but I am determined to work on it in the future. 

My biggest mistake that I’ve done is that my navigation on the mobile screen doesn’t work, but I was really fighting it and it just didn’t work for me, which makes me really sad, to be honest.

All to be said, I consider my work to be graded as B- because it has some issues but overall the website looks and works as it suppose to.

There are three pages I want you to grade:
Home, About, Peachy Cider.

Thank you for being so helpful the whole semester. :orange_heart::pray::skin-tone-2:

P.S. 
**_Markbot didn’t accept my web because it didn’t see my hover and doesn’t like my SVGs for some reason…_**
